CREATE TYPE user_role AS ENUM ('user', 'admin');
CREATE TYPE user_status AS ENUM ('pending', 'approved', 'rejected', 'blocked');

CREATE TABLE IF NOT EXISTS auth_service.users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role user_role NOT NULL DEFAULT 'user',
  status user_status NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auth_service.refresh_tokens (
  id UUID PRIMARY KEY NOT NULL,
  refresh_token TEXT UNIQUE NOT NULL,
  user_id UUID NOT NULL,
  expires_at TIMESTAMP with TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP + INTERVAL '30 day',
  created_at TIMESTAMP with TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_have_refresh_token
        FOREIGN KEY (user_id) REFERENCES auth_service.users (id)
        ON DELETE CASCADE
        ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS auth_service.password_reset_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reset_token UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  expires_at TIMESTAMP with TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP + INTERVAL '1 hour',
  created_at TIMESTAMP with TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_have_reset_token
        FOREIGN KEY (user_id) REFERENCES auth_service.users (id)
        ON DELETE CASCADE
        ON UPDATE RESTRICT
);

CREATE UNIQUE INDEX refresh_tokens_refresh_token_idx ON auth_service.refresh_tokens(refresh_token);
CREATE UNIQUE INDEX password_reset_tokens_reset_token_idx ON auth_service.password_reset_tokens(reset_token);

CREATE INDEX IF NOT EXISTS idx_users_name ON auth_service.users(name);
CREATE INDEX IF NOT EXISTS idx_users_email ON auth_service.users(email);
CREATE INDEX IF NOT EXISTS idx_users_status ON auth_service.users(status);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON auth_service.refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at ON auth_service.refresh_tokens(expires_at);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user_id ON auth_service.password_reset_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_expires_at ON auth_service.password_reset_tokens(expires_at);
