CREATE SCHEMA IF NOT EXISTS product_service;

CREATE TABLE IF NOT EXISTS product_service.products (
  product_id TEXT PRIMARY KEY,
  x DOUBLE PRECISION NOT NULL,
  y DOUBLE PRECISION NOT NULL,
  z DOUBLE PRECISION NOT NULL,
  weight DOUBLE PRECISION NOT NULL DEFAULT 0,
  quantity INTEGER NOT NULL DEFAULT 1,
  keep_upright BOOLEAN NOT NULL DEFAULT FALSE,
  stackable BOOLEAN NOT NULL DEFAULT TRUE,
  max_top_load DOUBLE PRECISION NOT NULL DEFAULT 0,
  minimum_support_ratio DOUBLE PRECISION NOT NULL DEFAULT 0,
  incompatible_tags TEXT[] NOT NULL DEFAULT '{}',
  allowed_rotations TEXT[] NULL,
  floor_only BOOLEAN NOT NULL DEFAULT FALSE,
  tags TEXT[] NOT NULL DEFAULT '{}',
  created_at TIMESTAMP with TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP with TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_products_created_at ON product_service.products(created_at);
